customhost = "employee.cgijukhgzoja.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "12345678"
customdb = "employee"
custombucket = "ongzhenghao-employee"
customregion = "us-east-1"
